name: Unit Testing for Plugins

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # TODO: Add paths.
  pull_request:
    # TODO: Add paths.
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit-test-main-plugin:
    name: 'PHP ${{ matrix.php }} / WP ${{ matrix.wp }}'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      mysql:
        image: mariadb:latest
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
          MARIADB_DATABASE: wordpress_test
          MARIADB_MYSQL_LOCALHOST_USER: 1
          MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
        ports:
          - 3306
        options: --health-cmd="healthcheck.sh --su-mysql --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']
        wp: ['latest']
        phpunit: ['9.3']
        include:
          - php: '8.2'
            phpunit: '9.6'
            wp: 'latest'

          - php: '8.1'
            phpunit: '9.6'
            wp: 'latest'

          - php: '8.0'
            phpunit: '9.3'
            wp: 'latest'

          - php: '7.3'
            phpunit: '7'
            wp: 'latest'

          - php: '7.2'
            phpunit: '7'
            wp: 'latest'

          - php: '7.1'
            phpunit: '7'
            wp: 'latest'

          - php: '7.0'
            phpunit: '7'
            wp: 'latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run WP Tests
        uses: ./.github/actions/setup-wp-tests
        with:
          wp: ${{ matrix.wp }}
          php: ${{ matrix.php }}
          phpunit: ${{ matrix.phpunit }}
          mysql-port: ${{ job.services.mysql.ports['3306'] }}
